version: '3.0'
services:
  app:
    container_name: levart-php
    build:
      context: '.'
      args:
        uid: 1000
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./:/var/www/html
      - ./docker/apache/log:/var/log/apache2
    ports:
      - 8000:80

  database:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - app-data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    volumes:
      - app-data:/data
    ports:
      - 8025:8025
      - 1025:1025
    
volumes:
  app-data: ~